### ISSUE TITLE
Sass implementation question

### ISSUE THREAD

**Issue by ai** [postcss/postcss-scss#1]
@chriseppstein reminded me about [Sass implamentation guidelines](http://sass-lang.com/implementation). I checked it myself and have few question:
1. SCSS will works like every other CSS parser with two extra option: nested rules and inline comment. Is it enough?
2. PostCSS parser doesn’t parse math or any other declaration values. They are just a string for them. Is it OK, that PostCSS SCSS parser will be limited in this way? Anyway PostCSS SCSS parser is not for compiling SCSS. It was created for simple tasks like CSSComb.
3. Do Sass community has some reference tests? So I can add them to Travis CI to be sure, that PostCSS SCSS parser can parse any SCSS source.

/cc @xzyfer

**Comment by ai** [comment]
From our site, I want to show you [PostCSS Parser Tests](https://github.com/postcss/postcss-parser-tests). It has many examples of compilcated CSS syntax cases. Which can be used to test Ruby/libsass SCSS parser too.

**Comment by xzyfer** [comment]
hey @ai 

For some context I've spent some time over the last couple months working a fork of PostCSS I'm calling Jamble that will have Sass, SCSS, and Less support. In my case I largely rewrote the tokenizer because word token makes the resolution too low to be useful for multiple language support.

> SCSS will works like every other CSS parser with two extra option: nested rules and inline comment. Is it enough?

Off the top of my head interpolants is the other big thing. For the most part they appear as PostCSS word tokens, but since they can also appear in the left or right or a declaration that _might_ need some attention.

>They are just a string for them. Is it OK, that PostCSS SCSS parser will be limited in this way?

This really comes down to your usecase. If you just want to build a comb tool you can get probably get away with this since math wont appear on left-hand-side of a declaration. 

However if you want a parser that's comparable to PostCSS you'll need higher resolution (more AST node types) than PostCSS. My usecase for Jamble is a SCSS linter so it has very high resolution (lots of AST node types).

> Do Sass community has some reference tests?

We use [Sass spec](https://github.com/sass/sass-spec). It's not complete Sass coverage, but it's close enough. It's what LibSass tests against.

**Comment by xzyfer** [comment]
@ai thanks for the link to the parser test. It would be useful to see how Sass/LibSass go. I've spent some time trying to integrate the w3c CSS test suit into the LibSass CI, but it's requires much more work.

**Comment by ai** [comment]
@xzyfer thanks for comments.

1. Yeap, interpolation contains `{`, I will add it to tokenizer. I should start tokenizing by `#{`?
2. W3C CSS test suit will be awesome! it is a correct [link](http://www.w3.org/Style/CSS/Test/Overview.en.html)? Do you know fast way to get test CSS files?
3. Integration between Jamble and PostCSS is in my task list. Maybe 6.0 or 7.0. I think we can start from 2 positions: you can make some tests without any compatibility issues to get quick feedback. And we will make AST better and better to add support to all plugins.
4. Sass spec is awesome. I will take all `**/input.scss` from repo and make smoke test in SCSS parser.

**Comment by ai** [comment]
@xzyfer @chriseppstein are you OK with current parser docs? I mention that is it only PostCSS AST parser, not a compiler https://github.com/postcss/postcss-scss

**Comment by ai** [comment]
@xzyfer I fix interpolations support cdec3c2
