### ISSUE TITLE
Consider ripping out single-line comments into separate plugin

### ISSUE THREAD

**Issue by cesarandreu** [postcss/postcss-scss#12]
Would you consider ripping out single-line comments into a separate plugin? 

I don't have a need to parse scss, however having both comment variations (`/**/`, `//`) available would be really convenient. Otherwise, something as simple as disabling a group of classes can become a hassle, if any of the classes have comments inside or around em.

**Comment by TrySound** [comment]
@cesarandreu It's parser, not plugin pack. If you need both comments, use it else use default postcss parser.

**Comment by TrySound** [comment]
@cesarandreu Also the difference between default and this parser is only parsing interpolation and comments.

**Comment by fabm22** [comment]
Hi I would like just to be sure, this plugin automatically transform "//" comments into "/* */" ? 
If so, is it possible to turn it off as one might actually want to keep the 'distinction' in final css ??

**Comment by ben-eb** [comment]
@fabm22 *`//` comments are not valid CSS.* So, keeping the distinction is not relevant for final CSS files. Also, translation between the comment types only happens if you use postcss-scss as a parser, with the default PostCSS stringifier. For SCSS -> SCSS transformations, the comment type is unmodified.

https://developer.mozilla.org/en-US/docs/Web/CSS/Comments

**Comment by fabm22** [comment]
Hi thanks for feedback. 
I'm sorry I was very tired lol. I didn't express me well. 
I'd like to keep the "feature" let's call it that of 'native' sass, which simply doesn't show anything coming from ```"//"``` comments. 
To keep this "feature" and still "pass" my css through this, i guess then I must "stay" in scss context ?
