### ISSUE TITLE
The postcss version should be set in dependencies

### ISSUE THREAD

**Issue by nzbin** [postcss/postcss-scss#134]
In some apps, the postcss-scss may not get the correct postcss version.
https://github.com/postcss/postcss-scss/blob/47ff0c51f4bf03d1c0867c911744bc5db174a839/package.json#L35-L37

**Comment by ai** [comment]
What do you suggest?

**Comment by nzbin** [comment]
use `dependencies`  instead of `peerDependencies` in `package.json`

**Comment by ai** [comment]
Using `dependencies` leads to a few big problems:

1. Because of the `npm` issue, you will have multiple copies of `postcss` which will bloat your `node_modules` and slow down CI.
2. `postcss-loader` and `postcss-scss` will use different PostCSS versions, and AST will be mixed of nodes from different PostCSS versions. It leads to very painful bugs.

These bugs affect everyone and is more painful for the commuinty.
