### ISSUE TITLE
SCSS nested properties issue

### ISSUE THREAD

**Issue by dryoma** [postcss/postcss-scss#39]
Sorry for bringing this up again. Yet the [previous issue](https://github.com/postcss/postcss-scss/issues/31) was about an exception thrown. An my question is about the very parsing.

Right now, parsing this

```scss
a {
  font: 10px/1 Arial {
    weight: 500;
  }
}
```
with PostCSS in postcss-scss syntax will result in the nested props block be considered a *nested ruleset*. And `font: 10px/1 Arial` will become a `selector` property of the corresponding PostCSS node object.

So the question is: is it in `postcss-scss` scope to correctly parse that `font: 10px/1 Arial` part? (it also applies to just `font:` with no value). I'm not sure how exactly it would be implemented; maybe a new node `type`, like `nested-decl`. Or just adding `nested-decl: true, prop: "font", value: "10px/1 Arial"` property set to an object. 

I suppose PostCSS would refuse to do it since the syntax is not standard. And yet, we have an obvious flaw in a parsing stack.

**Comment by ai** [comment]
It is valid SCSS syntax? O_o

**Comment by dryoma** [comment]
Yup, [it is](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#nested_properties). In fact, all these are (according to [Sassmeister](http://www.sassmeister.com/)):
```scss
font: {
  weight: 500;
}
```
```scss
font: 10px/1 Arial {
  weight: 500;
}
```
```scss
#{func-name($a: "something")}: 10px/1 Arial {
  weight: 500;
}
```
```scss
font: #{func-name($a: "something")}/1 Arial {
  weight: 500;
}
```

**Comment by ai** [comment]
Ouh :( I try to find time, but not soon. PR is welcome.

**Comment by dryoma** [comment]
First of all, thanks for refining #40 ! Totally missed prefixed pseudo classes and cases with parens.

Yet, now parsing nested props works only partially. The problems are:

1) Groups without a value for a root prop (`margin: { left: 10px; }`) are parsed as Rule - just as before. And they don't have any attributes that distinguish them as nested groups. A user will again have to do it himself.
2) some nested props groups are parsed as extended declaration, and others - as Ruls, which adds inconsistendy and requires more effort and more complex code to deal with;
3) `selector: "margin:"` doesn't make sense.

The [concern](https://github.com/postcss/postcss-scss/pull/40#issuecomment-242723342) behind that distinction was that `postcss-nested-props` would break otherwise. But @jedmao, its author, [said he is](https://github.com/jedmao/postcss-nested-props/issues/10#issuecomment-243049285) ok with all nested props groups be NestedDeclaration, as it was initially proposed.

So I suggest removing this distinction and parsing nested props groups consistently.

**Comment by ai** [comment]
Are you suggest to release major release of PostCSS core and change API only because of SCSS related feature, that didn’t used in the wild? ;)

C'om, it is SCSS parser. PostCSS is not a SCSS parser. If you need 100% support of SCSS features, you should use Sass.

PostCSS SCSS parser is only for Stylelint and postcss-sorting stuff. This is why nested props are parsed as `NestedDeclaration` to be compatible with all Stylelint linters (not 100% compatible).

**Comment by ai** [comment]
So, solutions:

1. If you need to convert `margin: 10px { top: 0 }` into `margin: 10px; margin-top: 0` — write your own `postcss-nested-props-sass` plugin. Of course, `postcss-nested-props` author doesn’t want to do it, because `NestedDeclaration` is not part of PostCSS core.
2. I will try to fix parsing nested props on the root.

**Comment by ai** [comment]
> some nested props groups are parsed as extended declaration, and others - as Ruls

Because

```css
margin: {
  top: 10px;
}
```

is part of PostCSS ecosystem

```css
margin: 0 {
  top: 10px;
}
```

is not part of PostCSS ecosystem, it is Sass feature.

**Comment by jedmao** [comment]
I'm still very confused about all of this, because [`postcss-nested-props`](https://github.com/jedmao/postcss-nested-props) [already supports](https://github.com/jedmao/postcss-nested-props/blob/master/test/plugin.ts#L32-L37) both of the examples above, as also [explained in the readme](https://github.com/jedmao/postcss-nested-props/blob/master/README.md#nested-properties). My only requirement has been to run the [`postcss-nested`](https://github.com/postcss/postcss-nested) plugin **_AFTER_** [`postcss-nested-props`](https://github.com/jedmao/postcss-nested-props).

That said, I don't know anything about the PostCSS SCSS parser, so if I had to write a separate plugin for that ecosystem then @ai is right. I have no interest in that.

**Comment by ai** [comment]
@jedmao I'm, problem is that we parses `margin: 10px {}` as NestedDeclaration with `node.type == "decl"` and `node.nodes`. We did it to be able work with Stylelint, so linter decisions rules works with `margin: 10px`.

@dryoma why do you need postcss-nested-props for SCSS sources?

**Comment by ai** [comment]
I agree, that consistently is good. But by adding consistently in `a: {}` and `a: b {}` in postcss-scss you will broke consistently in `a: {}` in postcss-scss and core parser.

I think second consistently is much not important, because they are much popular cases.

**Comment by dryoma** [comment]
I see your point, but 1) not all the code uses postcss-scss with postcss, (like postcss-nested-props - it doesn't use postcss-scss, so I am still confused why it was brought up), and 2) if this change is in a *major* version of postcss-scss, then those authors that don't want this change, probably won't get their code broken ('cause `"postcss-scss": "^0.1.7"` which is a usual form of dependencies in package.json, simply won't let the plugin upgrade from 0.x.x to 1.0.0). Let alone this will help the devs to get rid of kludges (от костылей) that are required now to simply distinguish normal rules from nested props. (and considering that both `margin: { top: 10px; }` and `margin: 0 { top: 10px; }` are used by postcss-nested-props and, thus, are part of the ecosystem, maybe adding support for them to PostCSS with the next major release is not such a silly idea. And @jedmao agreed that they are better off as Declarations).

And if `margin: { top: 10px; }` stays a Rule - well, nothing then nothing changes and one still can't rely on postcss-scss and implement their own hacks, as before.

**Comment by ai** [comment]
1. postcss-nested-props could be used with postcss-scss. So we should keep 2 different code for postcss abd postcss-scss in postcss-nested-props.
2. All you plan is that bigger inconsistency, that I am worry about. In current state we don't need to do anything and have smaller, more maintable code.

**Comment by dryoma** [comment]
Okaay, well, if that is your position then there is probably no reason to keep arguing :) In that case you just have said 'no' in the very start to save us both time :)
