### ISSUE TITLE
Comments with trailing */ report incorrect text

### ISSUE THREAD

**Issue by vjeux** [postcss/postcss-scss#64]
```css
@media (max-width: 1) {}
a {
  // element.style */
}
```

reports

```js
Comment {
  raws:
   { before: '\n  ',
     inline: true,
     left: ' ',
     right: '',
     text: 'element.style */' },
  type: 'css-comment',
  source:
   { start: { line: 3, column: 3 },
     input:
      Input {
        css: '@media (max-width: 1) {}\na {\n  // element.style */\n}\n',
        id: '<input css 1>' },
     end: { line: 3, column: 21 } },
  text: 'element.style *//*' }
```

notice that `text` is `'element.style *//*'`. It should be `'element.style */'`

**Comment by ai** [comment]
Sorry, I am on Cuba without Internet. I will look after June 9.

**Comment by ai** [comment]
Unfortunately, it is by design :(.

`postcss-scss` could be used only as parser (with regular CSS as stringifier). In this case PostCSS will compile `// a` to `/* a */`. Of course, in this case `// a */` will be compiled to `/* a */ */` and it will broke CSS.

I can add `.raws.scssText` with origin content. What do you think about it?

**Comment by vjeux** [comment]
Your solution would work for me.

**Comment by ai** [comment]
Ouh, it is already set in `Comment#raws.text` :D
