### ISSUE TITLE
Different node type for variables

### ISSUE THREAD

**Issue by Siilwyn** [postcss/postcss-scss#93]
:wave: hi there, just received a [PR to handle Sass variables differently](https://github.com/Siilwyn/css-declaration-sorter/pull/51). Instead of putting logic there it might make more sense to set the node type for variables differently in `postcss-scss`, thoughts?

**Comment by ai** [comment]
`node.type = variable` is not a correct PostCSS AST. It could break some plugins.

Also, `postcss-simple-vars` use the same variable syntax, but works with CSS syntax.

I think it is better to keep current behavior in parsers since PostCSS goal is to parse CSS. SCSS/Less/SugarSS support is just an addition hack.
